{{/*
if postgresql.global.postgresql.auth.existingSecret is not passed in, then we create a
secret to store the credentials without it being in a configmap in plaintext.
*/}}
{{- if and (not .Values.matrixAuthenticationServicePostgresql.global.postgresql.auth.existingSecret) (not .Values.matrixAuthenticationService.externalDatabase.existingSecret )}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "matrixAuthenticationService.fullname" . }}-db-secret
  labels:
    app.kubernetes.io/name: {{ include "matrixAuthenticationService.name" . }}
    helm.sh/chart: {{ include "matrixAuthenticationService.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  hostname: {{ include "matrixAuthenticationService.postgresql.hostname" . | b64enc | quote }}
  {{- if and .Values.matrixAuthenticationServicePostgresql.enabled (not .Values.matrixAuthenticationServicePostgresql.global.postgresql.auth.existingSecret) }}
  database: {{ .Values.matrixAuthenticationServicePostgresql.global.postgresql.auth.database | b64enc | quote }}
  username: {{ .Values.matrixAuthenticationServicePostgresql.global.postgresql.auth.username | b64enc | quote }}
  password: {{ .Values.matrixAuthenticationServicePostgresql.global.postgresql.auth.password | b64enc | quote }}
  {{- else if and .Values.matrixAuthenticationService.externalDatabase.enabled (not .Values.matrixAuthenticationService.externalDatabase.existingSecret) }}
  database: {{ .Values.matrixAuthenticationService.externalDatabase.database | b64enc | quote }}
  username: {{ .Values.matrixAuthenticationService.externalDatabase.username | b64enc | quote }}
  password: {{ .Values.matrixAuthenticationService.externalDatabase.password | b64enc | quote }}
  {{- end }}
{{- end }}
