{{- if not .Values.matrixAuthenticationService.mas.matrix.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "matrixAuthenticationService.fullname" . }}-matrix-secret
data:
  secret: {{ .Values.matrixAuthenticationService.mas.matrix.secret | b64enc | quote }}
{{- end }}
