name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'charts/**'

permissions:
  contents: write # allow actions to update gh-pages branch

jobs:
  release:
    environment: helm-release
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3.5
        id: helm-install
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Add dependency chart repos
        run: |
          helm repo add coturn https://small-hack.github.io/coturn-chart/
          helm repo add matrix-sliding-sync https://small-hack.github.io/matrix-sliding-sync-chart
          helm repo add matrix-authentication-service https://small-hack.github.io/matrix-authentication-service-chart
          helm dep update charts/matrix

      - name: Run chart-releaser
        id: helm-release
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          CR_GENERATE_RELEASE_NOTES: true
